In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X - X.mean()  # 核心逻辑：数据中心化（减去自身均值）

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(0., grad_fn=<MeanBackward0>)

In [9]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight) + self.bias
        return F.relu(linear)

In [10]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.8442,  0.7274,  0.5508],
        [-0.6592,  1.0482,  0.1238],
        [-1.7751, -1.9881,  1.3547],
        [ 0.1111, -0.5943,  1.7117],
        [-1.0019,  1.2401,  0.9714]], requires_grad=True)

In [11]:
linear(torch.rand(2, 5))

tensor([[0.0000, 1.3923, 1.9933],
        [0.0000, 0.2134, 3.1302]], grad_fn=<ReluBackward0>)

In [12]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[1.7926],
        [0.0000]], grad_fn=<ReluBackward0>)